import { PrismaClient, RecordType, Gender, CollaborationStatus, EngagementRateTier } from '@prisma/client';
import * as bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Clear existing data
  console.log('🗑️  Clearing existing data...');
  await prisma.person.deleteMany({});
  await prisma.category.deleteMany({});
  await prisma.refreshToken.deleteMany({});
  await prisma.user.deleteMany({});

  // Create admin user
  console.log('👤 Creating admin user...');
  const hashedPassword = await bcrypt.hash('password123', 10);
  const adminUser = await prisma.user.create({
    data: {
      email: 'admin@primeinfluencer.com',
      password: hashedPassword,
      name: 'Admin User',
      role: 'ADMIN',
    },
  });

  // Create categories from SQL data
  console.log('📁 Creating categories...');
  const categories = [
    { name: 'Lifestyle & Travel', description: 'Beauty, lifestyle, and travel content' },
    { name: 'Technology', description: 'Tech reviews and gadget showcases' },
    { name: 'Entertainment', description: 'Dance, comedy, and entertainment content' },
    { name: 'Food & Travel', description: 'Food reviews and travel experiences' },
    { name: 'Health & Wellness', description: 'Yoga, fitness, and wellness coaching' },
    { name: 'Automotive', description: 'Car reviews and motorsports content' },
    { name: 'DIY & Crafts', description: 'DIY projects and home decor' },
    { name: 'Gaming', description: 'Gaming streams and esports commentary' },
    { name: 'Fashion & Sustainability', description: 'Fashion and ethical manufacturing' },
    { name: 'Adventure Travel', description: 'Adventure travel and eco-tourism' },
  ];

  for (const category of categories) {
    await prisma.category.create({ data: category });
  }

  // Create people (individuals from SQL data - ALL 20 individuals)
  console.log('👥 Creating individuals...');
  const individuals = [
    {
      recordId: 'IND-001',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Somchai Prasert',
      preferredName: 'Somchai',
      gender: Gender.M,
      birthDate: new Date('1984-03-12'),
      email: 'somchai.prasert@example.com',
      phone: '+66-80-123-4567',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Marketing Manager',
      totalFollowersCount: 1800,
      interests: 'Fitness, Coffee',
      notes: 'Interested in supporting campaign logistics',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 1800,
      averageMonthlyReach: 5400,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://profiles.example.com/somchai-prasert',
      lastContactDate: new Date('2024-05-03'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-002',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Sudarat Wongwan',
      preferredName: 'Bee',
      gender: Gender.F,
      birthDate: new Date('1990-11-08'),
      email: 'sudarat.w@example.com',
      phone: '+66-85-222-1199',
      city: 'Chiang Mai',
      country: 'Thailand',
      occupation: 'Graphic Designer',
      totalFollowersCount: 950,
      interests: 'Art, Sustainable living',
      notes: 'Prefers remote collaboration schedules',
      secondaryPlatform: 'Behance',
      secondaryFollowersCount: 950,
      averageMonthlyReach: 2700,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH,EN',
      portfolioUrl: 'https://portfolio.example.com/sudarat-w',
      lastContactDate: new Date('2024-04-28'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-003',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Anan Chavalit',
      preferredName: 'Anan',
      gender: Gender.M,
      birthDate: new Date('1987-07-23'),
      email: 'anan.chavalit@example.com',
      phone: '+66-87-334-2201',
      city: 'Pattaya',
      country: 'Thailand',
      occupation: 'Event Producer',
      totalFollowersCount: 1500,
      interests: 'Concerts, Street food',
      notes: 'Experienced with large-scale event planning',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 1500,
      averageMonthlyReach: 6000,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-05-11'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-004',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Nattapong Srisuk',
      preferredName: 'Top',
      gender: Gender.M,
      birthDate: new Date('1994-05-15'),
      email: 'nattapong.srisuk@example.com',
      phone: '+66-81-555-6740',
      city: 'Khon Kaen',
      country: 'Thailand',
      occupation: 'Data Analyst',
      totalFollowersCount: 600,
      interests: 'Tech meetups, Gaming',
      notes: 'Strong analytical background for performance tracking',
      secondaryPlatform: 'GitHub',
      secondaryFollowersCount: 600,
      averageMonthlyReach: 4200,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH,EN',
      portfolioUrl: 'https://datafolio.example.com/nattapong',
      lastContactDate: new Date('2024-05-01'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-005',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Kamonchanok Siriphan',
      preferredName: 'Noey',
      gender: Gender.F,
      birthDate: new Date('1989-01-30'),
      email: 'kamonchanok.s@example.com',
      phone: '+66-93-214-7850',
      city: 'Phuket',
      country: 'Thailand',
      occupation: 'Hospitality Consultant',
      totalFollowersCount: 2100,
      interests: 'Luxury travel, Culinary arts',
      notes: 'Can provide venue partnerships on the islands',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2100,
      averageMonthlyReach: 6300,
      collaborationStatus: CollaborationStatus.WARM_LEAD,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-03-22'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-006',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Peerawat Kittisak',
      preferredName: 'Pete',
      gender: Gender.M,
      birthDate: new Date('1992-09-04'),
      email: 'peerawat.k@example.com',
      phone: '+66-82-908-2244',
      city: 'Udon Thani',
      country: 'Thailand',
      occupation: 'Videographer',
      totalFollowersCount: 12000,
      interests: 'Film production, Drone footage',
      notes: 'Owns 4K filming equipment and drones',
      secondaryPlatform: 'YouTube',
      secondaryFollowersCount: 12000,
      averageMonthlyReach: 45000,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://reels.example.com/peerawat',
      lastContactDate: new Date('2024-04-19'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-007',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Siriporn Chintana',
      preferredName: 'Fon',
      gender: Gender.F,
      birthDate: new Date('1995-12-18'),
      email: 'siriporn.c@example.com',
      phone: '+66-84-631-9920',
      city: 'Ratchaburi',
      country: 'Thailand',
      occupation: 'Community Manager',
      totalFollowersCount: 3500,
      interests: 'Book clubs, Local markets',
      notes: 'Active in regional non-profit initiatives',
      secondaryPlatform: 'Facebook',
      secondaryFollowersCount: 3500,
      averageMonthlyReach: 9200,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-05-07'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-008',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Thaksin Boonyarit',
      preferredName: 'Ken',
      gender: Gender.M,
      birthDate: new Date('1985-04-28'),
      email: 'thaksin.b@example.com',
      phone: '+66-95-120-5566',
      city: 'Ayutthaya',
      country: 'Thailand',
      occupation: 'Logistics Coordinator',
      totalFollowersCount: 900,
      interests: 'Cycling, History tours',
      notes: 'Can assist with transportation arrangements',
      secondaryPlatform: 'Line',
      secondaryFollowersCount: 900,
      averageMonthlyReach: 3200,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH',
      lastContactDate: new Date('2024-04-05'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-009',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Worarat Thanacha',
      preferredName: 'Wora',
      gender: Gender.F,
      birthDate: new Date('1993-10-22'),
      email: 'worarat.t@example.com',
      phone: '+66-86-447-3108',
      city: 'Nakhon Ratchasima',
      country: 'Thailand',
      occupation: 'Product Manager',
      totalFollowersCount: 2700,
      interests: 'UX research, Podcasts',
      notes: 'Interested in product feedback panels',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2700,
      averageMonthlyReach: 7800,
      collaborationStatus: CollaborationStatus.WARM_LEAD,
      languages: 'TH,EN',
      portfolioUrl: 'https://producthub.example.com/worarat',
      lastContactDate: new Date('2024-05-10'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-010',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Chakrit Maneerat',
      preferredName: 'Boss',
      gender: Gender.M,
      birthDate: new Date('1986-02-09'),
      email: 'chakrit.m@example.com',
      phone: '+66-89-771-2455',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Legal Advisor',
      totalFollowersCount: 3200,
      interests: 'Startup law, Basketball',
      notes: 'Can advise on contract review and compliance',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 3200,
      averageMonthlyReach: 9100,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-04-15'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-011',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Warunyu Pattanakul',
      preferredName: 'Ray',
      gender: Gender.M,
      birthDate: new Date('1991-04-17'),
      email: 'warunyu.p@example.com',
      phone: '+66-89-654-2210',
      city: 'Surat Thani',
      country: 'Thailand',
      occupation: 'Sound Engineer',
      totalFollowersCount: 1300,
      interests: 'Live music, Audio tech',
      notes: 'Available for on-site audio mixing',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 1300,
      averageMonthlyReach: 3600,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH,EN',
      portfolioUrl: 'https://sound.example.com/warunyu',
      lastContactDate: new Date('2024-05-08'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-012',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Kittiya Somsak',
      preferredName: 'Ploy',
      gender: Gender.F,
      birthDate: new Date('1996-12-03'),
      email: 'kittiya.s@example.com',
      phone: '+66-81-775-9034',
      city: 'Rayong',
      country: 'Thailand',
      occupation: 'Photographer',
      primaryPlatform: 'Instagram',
      followersCount: 4200,
      totalFollowersCount: 5800,
      interests: 'Street photography, Travel',
      notes: 'Provides on-shoot photography support',
      secondaryPlatform: 'Behance',
      secondaryFollowersCount: 1600,
      averageMonthlyReach: 12400,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://photos.example.com/kittiya',
      lastContactDate: new Date('2024-05-02'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-013',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Anongnat Srithong',
      preferredName: 'Ann',
      gender: Gender.F,
      birthDate: new Date('1988-07-29'),
      email: 'anongnat.s@example.com',
      phone: '+66-82-350-1129',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'PR Specialist',
      totalFollowersCount: 2400,
      interests: 'Media relations, CSR',
      notes: 'Experienced with press release drafting',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2400,
      averageMonthlyReach: 6800,
      collaborationStatus: CollaborationStatus.WARM_LEAD,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-04-26'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-014',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Tawan Rattanaporn',
      preferredName: 'Sun',
      gender: Gender.M,
      birthDate: new Date('1993-02-18'),
      email: 'tawan.r@example.com',
      phone: '+66-80-948-7756',
      city: 'Nonthaburi',
      country: 'Thailand',
      occupation: 'Copywriter',
      totalFollowersCount: 2100,
      interests: 'Brand storytelling, Podcasts',
      notes: 'Can assist with campaign messaging',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2100,
      averageMonthlyReach: 5900,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://copy.example.com/tawan',
      lastContactDate: new Date('2024-05-04'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-015',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Malai Phonsri',
      preferredName: 'Mai',
      gender: Gender.F,
      birthDate: new Date('1985-11-06'),
      email: 'malai.p@example.com',
      phone: '+66-83-617-4410',
      city: 'Chiang Mai',
      country: 'Thailand',
      occupation: 'Non-profit Coordinator',
      totalFollowersCount: 2800,
      interests: 'Community outreach, Education',
      notes: 'Can connect with local NGOs',
      secondaryPlatform: 'Facebook',
      secondaryFollowersCount: 2800,
      averageMonthlyReach: 7300,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH',
      lastContactDate: new Date('2024-04-29'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-016',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Phuwadol Nimit',
      preferredName: 'Dol',
      gender: Gender.M,
      birthDate: new Date('1990-09-12'),
      email: 'phuwadol.n@example.com',
      phone: '+66-95-201-6674',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Market Researcher',
      totalFollowersCount: 2500,
      interests: 'Consumer insights, Analytics',
      notes: 'Compiled previous audience reports',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2500,
      averageMonthlyReach: 8200,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH,EN',
      portfolioUrl: 'https://insights.example.com/phuwadol',
      lastContactDate: new Date('2024-05-05'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-017',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Kanyarat Deejai',
      preferredName: 'Yim',
      gender: Gender.F,
      birthDate: new Date('1997-01-25'),
      email: 'kanyarat.d@example.com',
      phone: '+66-94-880-3122',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'UI/UX Designer',
      primaryPlatform: 'Dribbble',
      followersCount: 3100,
      totalFollowersCount: 6400,
      interests: 'Product design, Accessibility',
      notes: 'Available for rapid prototyping sessions',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 3300,
      averageMonthlyReach: 8900,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://ux.example.com/kanyarat',
      lastContactDate: new Date('2024-05-06'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-018',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Surasak Preecha',
      preferredName: 'Sak',
      gender: Gender.M,
      birthDate: new Date('1982-06-09'),
      email: 'surasak.p@example.com',
      phone: '+66-96-552-4411',
      city: 'Chonburi',
      country: 'Thailand',
      occupation: 'Operations Supervisor',
      totalFollowersCount: 1900,
      interests: 'Logistics, Vendor management',
      notes: 'Handles supplier coordination',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 1900,
      averageMonthlyReach: 5600,
      collaborationStatus: CollaborationStatus.PROSPECT,
      languages: 'TH',
      lastContactDate: new Date('2024-04-21'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-019',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Chuenjit Maneesri',
      preferredName: 'Jit',
      gender: Gender.F,
      birthDate: new Date('1994-03-14'),
      email: 'chuenjit.m@example.com',
      phone: '+66-81-603-7742',
      city: 'Hat Yai',
      country: 'Thailand',
      occupation: 'Finance Analyst',
      totalFollowersCount: 2600,
      interests: 'Budgeting, Forecasting',
      notes: 'Can support campaign budgeting tasks',
      secondaryPlatform: 'LinkedIn',
      secondaryFollowersCount: 2600,
      averageMonthlyReach: 7000,
      collaborationStatus: CollaborationStatus.WARM_LEAD,
      languages: 'TH,EN',
      lastContactDate: new Date('2024-05-09'),
      createdById: adminUser.id,
    },
    {
      recordId: 'IND-020',
      recordType: RecordType.INDIVIDUAL,
      fullName: 'Ritthirong Kaewmanee',
      preferredName: 'Ice',
      gender: Gender.M,
      birthDate: new Date('1987-08-31'),
      email: 'ritthirong.k@example.com',
      phone: '+66-82-971-2245',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Event Technologist',
      totalFollowersCount: 2300,
      interests: 'Stage tech, Lighting',
      notes: 'Has inventory of stage lighting gear',
      secondaryPlatform: 'Facebook',
      secondaryFollowersCount: 2300,
      averageMonthlyReach: 6100,
      collaborationStatus: CollaborationStatus.CONTACTED,
      languages: 'TH,EN',
      portfolioUrl: 'https://eventsupport.example.com/ritthirong',
      lastContactDate: new Date('2024-05-07'),
      createdById: adminUser.id,
    },
  ];

  for (const individual of individuals) {
    await prisma.person.create({ data: individual });
  }

  // Create people (influencers from SQL data)
  console.log('⭐ Creating influencers...');
  const influencers = [
    {
      recordId: 'INF-011',
      recordType: RecordType.INFLUENCER,
      fullName: 'Napasorn Kittiya',
      preferredName: 'Napa',
      gender: Gender.F,
      birthDate: new Date('1996-06-14'),
      email: 'napasorn.kittiya@example.com',
      phone: '+66-90-452-1180',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Lifestyle Influencer',
      influencerCategory: 'Lifestyle & Travel',
      primaryPlatform: 'Instagram',
      followersCount: 185000,
      totalFollowersCount: 267000,
      engagementRate: 0.048,
      engagementRateTier: EngagementRateTier.LOW,
      interests: 'Beauty, Travel',
      notes: 'Collaborated with regional skincare brands',
      secondaryPlatform: 'YouTube',
      secondaryFollowersCount: 82000,
      averageMonthlyReach: 960000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://insta.example.com/napasorn',
      lastContactDate: new Date('2024-05-12'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-012',
      recordType: RecordType.INFLUENCER,
      fullName: 'Pattarapon Yodsakul',
      preferredName: 'Pat',
      gender: Gender.M,
      birthDate: new Date('1991-08-02'),
      email: 'pattarapon.y@example.com',
      phone: '+66-81-300-4577',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Tech Reviewer',
      influencerCategory: 'Technology',
      primaryPlatform: 'YouTube',
      followersCount: 320000,
      totalFollowersCount: 1060000,
      engagementRate: 0.062,
      engagementRateTier: EngagementRateTier.MEDIUM,
      interests: 'Gadget reviews, Tech news',
      notes: 'Hosts weekly livestream gadget showcases',
      secondaryPlatform: 'Facebook',
      secondaryFollowersCount: 740000,
      averageMonthlyReach: 1120000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://youtube.example.com/pattarapon',
      lastContactDate: new Date('2024-05-09'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-013',
      recordType: RecordType.INFLUENCER,
      fullName: 'Supakrit Limsiri',
      preferredName: 'Krit',
      gender: Gender.M,
      birthDate: new Date('1995-03-19'),
      email: 'supakrit.l@example.com',
      phone: '+66-94-730-8822',
      city: 'Chiang Mai',
      country: 'Thailand',
      occupation: 'Content Creator',
      influencerCategory: 'Entertainment',
      primaryPlatform: 'TikTok',
      followersCount: 410000,
      totalFollowersCount: 930000,
      engagementRate: 0.072,
      engagementRateTier: EngagementRateTier.HIGH,
      interests: 'Dance, Comedy skits',
      notes: 'Known for viral choreography challenges',
      secondaryPlatform: 'Instagram',
      secondaryFollowersCount: 520000,
      averageMonthlyReach: 1180000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH',
      portfolioUrl: 'https://tiktok.example.com/supakrit',
      lastContactDate: new Date('2024-05-08'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-014',
      recordType: RecordType.INFLUENCER,
      fullName: 'Lalita Chanapai',
      preferredName: 'Lita',
      gender: Gender.F,
      birthDate: new Date('1993-09-27'),
      email: 'lalita.c@example.com',
      phone: '+66-83-199-6644',
      city: 'Khon Kaen',
      country: 'Thailand',
      occupation: 'Food Blogger',
      influencerCategory: 'Food & Travel',
      primaryPlatform: 'Facebook',
      followersCount: 150000,
      totalFollowersCount: 410000,
      engagementRate: 0.038,
      engagementRateTier: EngagementRateTier.LOW,
      interests: 'Food reviews, Local travel',
      notes: 'Curates monthly food tour series',
      secondaryPlatform: 'YouTube',
      secondaryFollowersCount: 260000,
      averageMonthlyReach: 680000,
      collaborationStatus: CollaborationStatus.PAUSED,
      languages: 'TH,EN',
      portfolioUrl: 'https://foodjourney.example.com/lalita',
      lastContactDate: new Date('2024-04-30'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-015',
      recordType: RecordType.INFLUENCER,
      fullName: 'Prangthip Sae-Li',
      preferredName: 'Prang',
      gender: Gender.F,
      birthDate: new Date('1998-12-05'),
      email: 'prangthip.s@example.com',
      phone: '+66-92-504-7788',
      city: 'Phuket',
      country: 'Thailand',
      occupation: 'Wellness Coach',
      influencerCategory: 'Health & Wellness',
      primaryPlatform: 'Instagram',
      followersCount: 98000,
      totalFollowersCount: 243000,
      engagementRate: 0.055,
      engagementRateTier: EngagementRateTier.MEDIUM,
      interests: 'Yoga, Wellness lifestyle',
      notes: 'Offers branded mindfulness workshops',
      secondaryPlatform: 'TikTok',
      secondaryFollowersCount: 145000,
      averageMonthlyReach: 310000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://wellness.example.com/prangthip',
      lastContactDate: new Date('2024-05-06'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-016',
      recordType: RecordType.INFLUENCER,
      fullName: 'Arthit Dechapirom',
      preferredName: 'Art',
      gender: Gender.M,
      birthDate: new Date('1989-01-11'),
      email: 'arthit.d@example.com',
      phone: '+66-80-811-3490',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Automotive Host',
      influencerCategory: 'Automotive',
      primaryPlatform: 'YouTube',
      followersCount: 560000,
      totalFollowersCount: 940000,
      engagementRate: 0.044,
      engagementRateTier: EngagementRateTier.LOW,
      interests: 'Automotive reviews, Motorsports',
      notes: 'Partnered with major car manufacturers',
      secondaryPlatform: 'Instagram',
      secondaryFollowersCount: 380000,
      averageMonthlyReach: 1250000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://auto.example.com/arthit',
      lastContactDate: new Date('2024-05-02'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-017',
      recordType: RecordType.INFLUENCER,
      fullName: 'Chanapa Wattanakorn',
      preferredName: 'Cherry',
      gender: Gender.F,
      birthDate: new Date('1994-07-21'),
      email: 'chanapa.w@example.com',
      phone: '+66-88-610-2355',
      city: 'Chiang Rai',
      country: 'Thailand',
      occupation: 'DIY Creator',
      influencerCategory: 'DIY & Crafts',
      primaryPlatform: 'TikTok',
      followersCount: 230000,
      totalFollowersCount: 540000,
      engagementRate: 0.081,
      engagementRateTier: EngagementRateTier.HIGH,
      interests: 'DIY crafts, Home decor',
      notes: 'Runs monthly live DIY workshops',
      secondaryPlatform: 'YouTube',
      secondaryFollowersCount: 310000,
      averageMonthlyReach: 870000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH',
      portfolioUrl: 'https://diy.example.com/chanapa',
      lastContactDate: new Date('2024-05-11'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-018',
      recordType: RecordType.INFLUENCER,
      fullName: 'Veeravit Suttipong',
      preferredName: 'Vee',
      gender: Gender.M,
      birthDate: new Date('1992-05-09'),
      email: 'veeravit.s@example.com',
      phone: '+66-98-220-5410',
      city: 'Pattaya',
      country: 'Thailand',
      occupation: 'Gaming Streamer',
      influencerCategory: 'Gaming',
      primaryPlatform: 'Twitch',
      followersCount: 87000,
      totalFollowersCount: 307000,
      engagementRate: 0.036,
      engagementRateTier: EngagementRateTier.LOW,
      interests: 'Gaming, Esports commentary',
      notes: 'Casts regional esports tournaments',
      secondaryPlatform: 'YouTube',
      secondaryFollowersCount: 220000,
      averageMonthlyReach: 640000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://twitch.example.com/veeravit',
      lastContactDate: new Date('2024-05-05'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-019',
      recordType: RecordType.INFLUENCER,
      fullName: 'Jirapa Maneekul',
      preferredName: 'June',
      gender: Gender.F,
      birthDate: new Date('1990-10-03'),
      email: 'jirapa.m@example.com',
      phone: '+66-87-903-1188',
      city: 'Bangkok',
      country: 'Thailand',
      occupation: 'Fashion Advocate',
      influencerCategory: 'Fashion & Sustainability',
      primaryPlatform: 'Instagram',
      followersCount: 205000,
      totalFollowersCount: 515000,
      engagementRate: 0.052,
      engagementRateTier: EngagementRateTier.MEDIUM,
      interests: 'Fashion, Sustainability',
      notes: 'Campaigns for ethical manufacturing practices',
      secondaryPlatform: 'Facebook',
      secondaryFollowersCount: 310000,
      averageMonthlyReach: 880000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://style.example.com/jirapa',
      lastContactDate: new Date('2024-05-04'),
      createdById: adminUser.id,
    },
    {
      recordId: 'INF-020',
      recordType: RecordType.INFLUENCER,
      fullName: 'Bordin Adulchai',
      preferredName: 'Din',
      gender: Gender.M,
      birthDate: new Date('1988-11-30'),
      email: 'bordin.a@example.com',
      phone: '+66-96-512-7744',
      city: 'Chiang Mai',
      country: 'Thailand',
      occupation: 'Travel Vlogger',
      influencerCategory: 'Adventure Travel',
      primaryPlatform: 'YouTube',
      followersCount: 450000,
      totalFollowersCount: 740000,
      engagementRate: 0.057,
      engagementRateTier: EngagementRateTier.MEDIUM,
      interests: 'Adventure travel, Eco tourism',
      notes: 'Produces bilingual content for ASEAN audiences',
      secondaryPlatform: 'Instagram',
      secondaryFollowersCount: 290000,
      averageMonthlyReach: 1020000,
      collaborationStatus: CollaborationStatus.ACTIVE,
      languages: 'TH,EN',
      portfolioUrl: 'https://voyage.example.com/bordin',
      lastContactDate: new Date('2024-05-10'),
      createdById: adminUser.id,
    },
  ];

  for (const influencer of influencers) {
    await prisma.person.create({ data: influencer });
  }

  console.log('✅ Seed completed successfully!');
  console.log('📊 Created:');
  console.log(`   - 1 admin user (admin@primeinfluencer.com / password123)`);
  console.log(`   - ${categories.length} categories`);
  console.log(`   - ${individuals.length} individuals`);
  console.log(`   - ${influencers.length} influencers`);
  console.log(`   - Total: ${individuals.length + influencers.length} people`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
